spring:
  application:
    name: api-service
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %highlight(%-5level) %clr(%-40.40logger{39}){cyan} traceID=%X{trace_id} %clr(:){faint} %m%n%wEx"